---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  labels: 
    app:  users-svc
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
     app: users
  template:
    metadata:
      labels:
        app:  users
        env:  dev
    spec: 
      containers:
        - name: web
          image:  shaikkhajaibrahim/libuserssvc:1.0
          env:
            - name: DATABASE_URL
              value:  postgresql://user:password@users-db:@:5432/usersdb
            - name: SECRET_KEY
              value:  YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k
          ports:
            - containerPort:  8000
          resources:
            requests:
              cpu:  200m
              memory: 200Mi
            limits:
              cpu:  250m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app:  users



